<a href="https://colab.research.google.com/github/net4troll/DS-GMC-WS/blob/main/Ali_REZOUALI_NumPy_numpy_%2Bexercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Partie Rappel!!



In [ ]:
liste

['1', '111', '2', '523', '750']

In [ ]:
s= 0
for i in liste:
  s = s + int(i)
print(s)


13


In [ ]:
def multiple(a):
  p = 1
  for i in a :
    p*= i 
  return p


In [ ]:
a = [1,2,3,4,56,8]
multiple(a)

10752

In [ ]:
multiple(({1,2,3,4}))

24

In [ ]:
multiple([1,2,3,4])



---



---

#Numpy

In [ ]:
import numpy as np

In [ ]:
x = np.array([[[1,2.5,4,5], [14,7,4,5],[5,4,5,2]]], dtype = float) #dtype pour unifier et convertir 

In [ ]:
x

array([[[ 1. ,  2.5,  4. ,  5. ],
        [14. ,  7. ,  4. ,  5. ],
        [ 5. ,  4. ,  5. ,  2. ]]])

In [ ]:
x.ndim

3

In [ ]:
a = np.array([1,2,3])

In [ ]:
a.ndim

1

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

#The basics!!!!!

In [ ]:
a = np.array([1.2,"2",3],dtype=float)

In [ ]:
a

array([1.2, 2. , 3. ])

In [ ]:
b = np.array([[[9,8,7,4],[6,5,4,6],[6,5,4,6]],
               
              [[9,8,7,4],[6,5,4,6],[6,5,4,6]],
              
              [[9,8,7,4],[6,5,4,6],[6,5,4,6]]
              ])


In [ ]:
b

array([[[9, 8, 7, 4],
        [6, 5, 4, 6],
        [6, 5, 4, 6]],

       [[9, 8, 7, 4],
        [6, 5, 4, 6],
        [6, 5, 4, 6]],

       [[9, 8, 7, 4],
        [6, 5, 4, 6],
        [6, 5, 4, 6]]])

In [ ]:
b.shape# num de : dim, number ligne, number of colomns

In [ ]:
x = np.array([[1,2,3],
              [14,15,1]])

In [ ]:
x.shape  #num de ligne et colonne

(2, 3)

In [ ]:
x.ndim

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.size #nombre de ligne * nombre de colonne

6


#Accessing/Changing specific elements

In [ ]:
x

array([[353, 353, 353],
       [353, 353, 353]])

In [ ]:
x[:,:]=353

In [ ]:
x[1,2]

353

In [ ]:
x = np.array([[1,22,8,4],
              [4,15,10,7]])

In [ ]:
x[:,2]

array([ 8, 10])

In [ ]:
x[1,1:3]

array([15, 10])

In [ ]:
x = np.array([[1,22,8,4,9,27,8],
              [4,15,10,7,19,12,18]])
x

array([[ 1, 22,  8,  4,  9, 27,  8],
       [ 4, 15, 10,  7, 19, 12, 18]])

In [ ]:
x[x< 12]

array([1, 8, 4, 9, 8, 4, 5, 7])

In [ ]:
# [startindex:endindex:stepsize]
x[:, 1:-1:2]

array([22,  4, 27])

In [ ]:
x[:,2]

array([ 8, 10])

In [ ]:
x = 333333333333
x

333333333333

In [ ]:
x[1,2] = 5

In [ ]:
x

array([[ 1, 22,  8,  4,  9, 27,  8],
       [ 4, 15,  5,  7, 19, 12, 18]])

#Initialization of an array !!

In [ ]:
d1 = np.ones((2,3),dtype=float) + 5

In [ ]:
d2 = np.ones((2,3),dtype=float) + 7

In [ ]:
d1[1,2] = 17 *5
d1

array([[ 6.,  6.,  6.],
       [ 6.,  6., 85.]])

In [ ]:
array1 = np.array([1,2,3,4])
array2 = np.array([4,5,6,7])

In [ ]:
array1 * array2 

array([ 4, 10, 18, 28])

In [ ]:
np.full((2,4),'100000007')


array([['100000007', '100000007', '100000007', '100000007'],
       ['100000007', '100000007', '100000007', '100000007']], dtype='<U9')

In [ ]:
c= np.full((2,3),7)
c

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.full_like(c, 9) #c c'est notre matrice 

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:

# Random decimal numbers
np.random.rand(4,2)

array([[0.92372676, 0.96452542],
       [0.51055142, 0.36748303],
       [0.33130574, 0.17273168],
       [0.71207748, 0.10480015]])

In [ ]:
np.random.randint(-4,8, size=(3,3)) #des valeurs entre -4 et 8,  avec la taille 3*3

array([[ 0,  1,  1],
       [-4,  5,  2],
       [ 4,  5, -3]])

In [ ]:
# The identity matrix
np.identity(7)

In [ ]:
# Repeat an array
arr = np.array([[1,2,3,-2,0,11,15,9]])
arr[(arr > 0) & (arr < 10)] 

array([1, 2, 3, 9])

In [ ]:
arr[(arr <2) & (arr<10)]

array([ 1, -2,  0])


# NumPy exercises


In [ ]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.21.6


In [ ]:
reshaping = np.array([1,2,3,4,5,6])
reshaping

array([1, 2, 3, 4, 5, 6])

In [ ]:
reshaping.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
liste = list(reshaping)

In [ ]:
type(liste)

list

In [ ]:
array3 = np.array(liste)

In [ ]:
type(array3)

numpy.ndarray

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [ ]:
# your code goes here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])



### Create a numpy array with values ranging from 10 to 49

In [ ]:
np.random.randint(10,50,size=(1,9))

array([[36, 41, 10, 47, 21, 13, 41, 48, 23]])



### Create a numpy matrix of 2*2 integers, filled with ones.

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])



### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [ ]:
# your code goes here
np.ones((3,2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

Exemple : https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html

In [ ]:
# your code goes here
X  = np.ones((3,2), dtype=float)
np.zeros_like(X)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])



### Create a numpy matrix of 4*4 integers, filled with fives.

https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-13.php 


In [ ]:
# your code goes here
np.full((4,4),5,dtype=int)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [ ]:
# your code goes here
np.full_like(X,7)

array([[7., 7.],
       [7., 7.],
       [7., 7.]])



### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [ ]:
# your code goes here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])



### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [ ]:
# your code goes here
np.random.randint(1,11, size=(3,3))

array([[ 3,  4,  5],
       [ 8,  7, 10],
       [ 8,  7,  9]])



### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [ ]:
# your code goes here
np.random.ranf(size=(3,3,3))

array([[[0.8575945 , 0.50013804, 0.31213338],
        [0.81676076, 0.02086063, 0.69043731],
        [0.03923775, 0.25770738, 0.14326868]],

       [[0.61080704, 0.28373151, 0.13024502],
        [0.52870062, 0.43604255, 0.27161883],
        [0.89567331, 0.61624709, 0.75435231]],

       [[0.79433662, 0.55837263, 0.24520555],
        [0.62339759, 0.99016408, 0.06681728],
        [0.99760827, 0.45545399, 0.59230822]]])



### Given the X python list convert it to an Y numpy array

In [ ]:
# your code goes here
X = [1,3,7,2,9,18,10]
Y = np.array(X)

numpy.ndarray



### Given the X numpy array, make a copy and store it on Y.

In [ ]:
# your code goes here
X = np.random.randint(1,10, size=(1,10))
Y = X.copy()
Y

array([[8, 5, 3, 7, 1, 5, 3, 1, 3, 1]])



### Create a numpy array with numbers from 1 to 10

In [ ]:
# your code goes here
X = np.array(list(range(1,11)))
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



### Create a numpy array with the odd numbers between 1 to 10

In [ ]:
# your code goes here
X = np.array(list(range(1,11,2)))
X

array([1, 3, 5, 7, 9])

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [ ]:
# your code goes here
Z = np.array(list(range(0,9))).reshape(3,3)



### Show the memory size of the given Z numpy matrix

In [ ]:
# your code goes here
Z.itemsize

8

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [ ]:
# your code goes here
print(X[0])
print(Z[0][0])

1
0




### Given the X numpy array, show it's last element

In [ ]:
# your code goes here
print(X[-1])
print(Z[-1][-1])

9
8




### Given the X numpy array, show it's first three elements

In [ ]:
# your code goes here
print(X[:3])
print(Z[:1][:])

[1 3 5]
[[0 1 2]]




---



### Create a numpy array with numbers from 1 to 10, in descending order.

In [ ]:
# your code goes here
" https://www.kite.com/python/answers/how-to-sort-a-numpy-array-in-descending-order-in-python



### Given the X numpy array, show all middle elements

In [ ]:
# your code goes here




### Given the X numpy array, show the elements in reverse position

In [ ]:
# your code goes here




### Given the X numpy array, show the elements in an odd position

In [ ]:
# your code goes here




### Given the X numpy matrix, show the first row elements

In [ ]:
# your code goes here




### Given the X numpy matrix, show the last row elements

In [ ]:
# your code goes here




### Given the X numpy matrix, show the first element on first row

In [ ]:
# your code goes here




### Given the X numpy matrix, show the last element on last row

In [ ]:
# your code goes here




### Given the X numpy matrix, show the last two elements on the last two rows

In [ ]:
# your code goes here


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [ ]:
# your code goes here




### Reverse the given numpy array (first element becomes last)

In [ ]:
# your code goes here




### Order (sort) the given numpy array

In [ ]:
# your code goes here




### Given the X numpy array, set the fifth element equal to 1

In [ ]:
# your code goes here




### Given the X numpy array, change the 50 with a 40

In [ ]:
# your code goes here



### Given the X numpy matrix, change the last row with all 1

In [ ]:
# your code goes here



### Given the X numpy matrix, change the last item on the last row with a 0

In [ ]:
# your code goes here



### Given the X numpy matrix, add 5 to every element

In [ ]:
# your code goes here



## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [ ]:
# your code goes here
a = np.array([-4,5,1,2,3,5])
a<=1

array([ True, False,  True, False, False, False])


### Given the X numpy array, get the negative elements

In [ ]:
# your code goes here
a[a<0]

array([-4])


### Given the X numpy array, get numbers higher than 5

In [ ]:
# your code goes here



### Given the X numpy array, get numbers higher than the elements mean

In [ ]:
# your code goes here
a[a <a.mean()]

array([-4,  1])


### Given the X numpy array, get numbers equal to 2 or 10

In [ ]:
# your code goes here
a [(a == 2) | (a == 10)]

array([2])


## Summary statistics

### Given the X numpy array, show the sum of its elements

In [ ]:
# your code goes here



12


### Given the X numpy array, show the mean value of its elements

In [ ]:
# your code goes here


In [ ]:
a

array([-4,  5,  1,  2,  3,  5])

### Given the X numpy array, show the max value of its elements

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)



# Answer The following questions!

In [ ]:
# your code goes here
import seaborn as sns

In [ ]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
df = sns.load_dataset('titanic')

In [ ]:
df[df.sex=="male"]

survived  pclass   sex   age  sibsp  parch     fare embarked   class  \
0           0       3  male  22.0      1      0   7.2500        S   Third   
4           0       3  male  35.0      0      0   8.0500        S   Third   
5           0       3  male   NaN      0      0   8.4583        Q   Third   
6           0       1  male  54.0      0      0  51.8625        S   First   
7           0       3  male   2.0      3      1  21.0750        S   Third   
..        ...     ...   ...   ...    ...    ...      ...      ...     ...   
883         0       2  male  28.0      0      0  10.5000        S  Second   
884         0       3  male  25.0      0      0   7.0500        S   Third   
886         0       2  male  27.0      0      0  13.0000        S  Second   
889         1       1  male  26.0      0      0  30.0000        C   First   
890         0       3  male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
4      man        True  NaN  Southampton    no   True  
5      man        True  NaN   Queenstown    no   True  
6      man        True    E  Southampton    no   True  
7    child       False  NaN  Southampton    no  False  
..     ...         ...  ...          ...   ...    ...  
883    man        True  NaN  Southampton    no   True  
884    man        True  NaN  Southampton    no   True  
886    man        True  NaN  Southampton    no   True  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[577 rows x 15 columns]

# Average age of woman category.

In [ ]:
df[df.alive=="yes"]&df[df.sex=="male"]



TypeError: ignored

## Average age of man category.

In [ ]:
df[(df.alive == "yes", df.sex =="male")]

TypeError: ignored

## The lowest age among alone woman.

survived  pclass   sex   age  ...  deck  embark_town  alive  alone
0           0       3  male  22.0  ...   NaN  Southampton     no  False
4           0       3  male  35.0  ...   NaN  Southampton     no   True
5           0       3  male   NaN  ...   NaN   Queenstown     no   True
6           0       1  male  54.0  ...     E  Southampton     no   True
12          0       3  male  20.0  ...   NaN  Southampton     no   True
..        ...     ...   ...   ...  ...   ...          ...    ...    ...
883         0       2  male  28.0  ...   NaN  Southampton     no   True
884         0       3  male  25.0  ...   NaN  Southampton     no   True
886         0       2  male  27.0  ...   NaN  Southampton     no   True
889         1       1  male  26.0  ...     C    Cherbourg    yes   True
890         0       3  male  32.0  ...   NaN   Queenstown     no   True

[537 rows x 15 columns]

. 